### ISSUE TITLE
Inferno support (was: Which maps to use by default)

### ISSUE THREAD

**Issue by mariusandra** [mariusandra/pigeon-maps#1]
Currently the default maps are from Wikimedia. I'm not sure if we can use them. Must be investigated.

**Comment by degroote22** [comment]
Wow. I'm impressed by this project. I'll try to use it on my project.

On the subject of wikimedia maps I believe we can't use them like this but they use Open Street Map as th e map provider. OSM's api also is not recommended to this use case.

We should be using a paid OSM provider with a generous free tier. I was trying to get out of google maps and while researching I found [Mapbox](https://www.mapbox.com). It's used by a lot of big players and it has 50k free map views per month. That's enough to kickstart a project.

https://www.mapbox.com/pricing/

Other providers can be found here: https://switch2osm.org/providers/

**Comment by mariusandra** [comment]
Hey, thanks for the comments and investigation!

I didn't see your edits this morning, so I just went ahead and added OSM and Mapbox tiles to the demo app:

<img width="610" alt="screen shot 2016-12-21 at 09 04 17" src="https://cloud.githubusercontent.com/assets/53387/21381665/ec1a7d1a-c75c-11e6-87a2-e6d049474504.png">

About Inferno, I've been evaluating it myself for my own app in recent weeks. I like what @trueadm & co are doing! :)

The only gripe I have is that as a plugin maintainer you're sort of forced to write two versions of your package - one for React and one for Inferno, with a 99% overlap in code. I'd ideally like to avoid that, and bundle both options in one package. Possibly with different import paths (`import Map from 'pigeon-maps/inferno'`), or some `webpack-inferno-loader` that strips out the React (proptypes, imports, etc) and replaces it with inferno-specific code.

Otherwise we're going to pollute NPM with packages like "pigeon-marker", "pigeon-marker-infero", "pigeon-overlay", "pigeon-overlay-inferno", etc.

Any ideas on this?

**Comment by mariusandra** [comment]
Just a quick extra note, at your `inferno-pigeon` firebase link, I see this:

<img width="669" alt="screen shot 2016-12-21 at 09 18 30" src="https://cloud.githubusercontent.com/assets/53387/21381974/8379cdf4-c75e-11e6-9c31-c175391d8a8e.png">

I think OSM tiles don't support the `@2x` retina tag :).

**Comment by trueadm** [comment]
@degroote22 Hey, I'd like to help you with the issues you had with Inferno. You shouldn't be seeing any performance issues – so there's likely a compatibility difference at play.

**Comment by mariusandra** [comment]
@trueadm @degroote22 I'm throwing in a wild guess here without investigating any code.

The pigeon-maps component calls `this.setState()` every now and then. Afterwards is it's a controlled component, it will call `this.props.onBoundsChanged()`, which then passes in new props. 

I had the issue with one `react-typeahead` component that I was trying to *infernoize* ([point #2 here](https://github.com/trueadm/inferno/issues/503#issuecomment-266308687)), where the `setState()` immediately triggered a re-render of the entire component.

It could be a similar case here.

**Comment by trueadm** [comment]
@mariusandra almost definitely the case. Inferno's `setState` prefers synchronous updates. You can force it to be async (and get a perf win) by passing in a NOOP function as the callback for `setState`. I bet that fixes the performance issues.

**Comment by mariusandra** [comment]
@degroote22 can you check if doing this fixes the performance issue you reported?

@trueadm any suggestions on how to release the component for react and inferno without the maintenance overhead of managing two packages... and without maintaining two versions of each plugin?

I'll look into this over the holidays if no solution exists currently.

**Comment by trueadm** [comment]
@mariusandra you could abstract the main APIs and have a different command to build different webpack configs (as Inferno has its own babel JSX plugin). I'll need to think about how to best go about this over the next few days. I believe Next.js are looking to do something similar too.

**Comment by degroote22** [comment]
I'll try what @trueadm suggested this afternoon and later I'll post my findings.

**Comment by degroote22** [comment]
@trueadm, the noop function is
`const NOOP = () => {}`?
If it is, then...

As far as my eye could see it, there was only a minor improvement. React is still better imho.
I took some screenshots of the react perf tools. Performance is that bad on both react and inferno bc I'm compiling something right now. My pc will probably melt.

On the following 3 tests I scrolled the page as fast as I could.
**react - pigeon maps demo**
![react](https://cloud.githubusercontent.com/assets/12750442/21396978/2e25aeb0-c789-11e6-8005-e8e8a7ecf9fe.png)

**inferno - no noop**
![no noop](https://cloud.githubusercontent.com/assets/12750442/21397062/77d7fdba-c789-11e6-988a-fdc6fbb13969.png)

**inferno - noop**
![noop](https://cloud.githubusercontent.com/assets/12750442/21397097/95103ff0-c789-11e6-9d0c-0f29d2422c8e.png)

Then, I recorded some light usage of the page.
**react**
![react normal](https://cloud.githubusercontent.com/assets/12750442/21397105/9e7afa80-c789-11e6-8853-62f25b61fadd.png)

**inferno**
![pigeon normal](https://cloud.githubusercontent.com/assets/12750442/21397101/98f4ee7c-c789-11e6-9d74-9c7473d60353.png)

**Comment by degroote22** [comment]
![fdps drops](https://cloud.githubusercontent.com/assets/12750442/21398170/873f8440-c78d-11e6-84be-813b667caec5.png)

**Comment by trueadm** [comment]
So you've fixed your issue? What did you change in your port? Are you also throttling/denouncing the scroll event? That should help too

**Comment by degroote22** [comment]
@trueadm, it is fixed. The component works very nicely with Inferno. Setting the callback to NOOP is the only thing I did inferno-wise.
Debouncing and throttling @mariusandra knows about. I haven't had the time to read the full source yet.
Thanks for your interest! That's awsome!

**Comment by trueadm** [comment]
Oh I thought you tried the NOOP trick and it wasn't working? Did you not apply it correctly?

**Comment by degroote22** [comment]
@trueadm forgive me for not explaining it correctly.
Setting the callback to NOOP increased the performance of the application but was not enough to surpass React's.
React was "telling" chrome to "compose layers"
![compose layers](https://cloud.githubusercontent.com/assets/12750442/21400053/63c8d446-c795-11e6-97a5-456438a7d0ae.png)
 less times than Inferno and the bottleneck was this operation.
I made some changes and now that this operation is no longer costly Inferno's performance is better than React's.
I hope you can get it now... I'm struggling a bit to communicate in English, it is not my mother language as you can tell.

**Comment by mariusandra** [comment]
@degroote22 your port does feel crazy fast now! These pics say it all:

React + willChange with a 5x slowdown:
<img width="937" alt="screen shot 2016-12-21 at 20 05 48" src="https://cloud.githubusercontent.com/assets/53387/21402464/e85c5f0c-c7b8-11e6-857f-fba68e5a07ed.png">

Inferno + willChange with a 5x slowdown:
<img width="935" alt="screen shot 2016-12-21 at 20 05 51" src="https://cloud.githubusercontent.com/assets/53387/21402472/f17e9136-c7b8-11e6-908e-8e166798ec6e.png">

While both manage 60FPS under those conditions, inferno does much less work per frame! From 9-11ms with React to 5-8ms with Inferno. 🔥 

However something changed and now on https://pigeon-inferno.firebaseapp.com/ the animation is a bit jerky. It's fast and smooth, but when you let go of dragging, it jumps momentarily back to where you started dragging, and then animates. I guess you see it yourself?

In any case, great work!

Unfortunately I can't help much more with debugging today. It's the holiday rush period where a week's worth of work must be condensed into a day! 🎅 🎄 

One open question is still how to combine the Inferno and React versions together into one package for distribution. If nobody else has time, I'll try to figure out a solution after the holidays.

Cheers!

**Comment by degroote22** [comment]
I see it now... Will look into it.

**Comment by mariusandra** [comment]
Hello and Merry Christmas! 🎄 🌟 🎅 

I managed to hack together a version of `pigeon-maps` that outputs both an Inferno and a React build from the same codebase. It's still rough, so let me know if you have any ideas on how to improve it.

The code is in the [inferno branch](https://github.com/mariusandra/pigeon-maps/tree/inferno).

Basically, I set up two different babel environments. One is called `react` and one the other is `inferno`.

My [`.babelrc`](https://github.com/mariusandra/pigeon-maps/blob/inferno/.babelrc) looks like this:

```json
{
  "env": {
    "inferno": {
      "presets": ["es2015", "stage-0"],
      "plugins": [
        "inferno",
        "./utils/babel-env-inline",
        "minify-dead-code-elimination"
      ]
    },
    "react": {
      "presets": ["es2015", "stage-0", "react"],
      "plugins": [
        "./utils/babel-env-inline",
        "minify-dead-code-elimination"
      ],
    }
  }
}
```

Then in the code, I import all `React`, `Inferno`, etc from a file called [`infact`](https://github.com/mariusandra/pigeon-maps/blob/inferno/src/infact.js) (inferno + react) that looks like this:

```js
if (process.env.BABEL_ENV === 'inferno') {
  exports.Inferno = require('inferno')
  exports.ReactDOM = exports.Inferno
  exports.Component = require('inferno-component')
  exports.PropTypes = {}
}
if (process.env.BABEL_ENV === 'react') {
  exports.React = require('react')
  exports.ReactDOM = require('react-dom')
  exports.Component = exports.React.Component
  exports.PropTypes = exports.React.PropTypes
}
```

I use a custom babel plugin called [`babel-env-inline`](https://github.com/mariusandra/pigeon-maps/blob/inferno/utils/babel-env-inline.js), which is very strongly inspired by the [`transform-node-env-inline`](https://github.com/babel/babili/tree/master/packages/babel-plugin-transform-node-env-inline) babel plugin. 

It replaces each occurrence of `process.env.BABEL_ENV === 'something'` with either a `true` or a `false`. This way the `infact.js` under `lib/inferno.js` [looks like this](https://github.com/mariusandra/pigeon-maps/blob/inferno/lib/inferno/infact.js).


    "build:lib": "npm run build:lib:react && npm run build:lib:inferno",
    "build:lib:inferno": "BABEL_ENV=inferno ./node_modules/.bin/babel src --out-dir lib/inferno",
    "build:lib:react": "BABEL_ENV=react ./node_modules/.bin/babel src --out-dir lib/react",

**Comment by mariusandra** [comment]
@degroote22 could you check out the branch and add your fixes regarding `setState`, `React.Children`, etc?

**Comment by degroote22** [comment]
I'm on it.
I submitted a PR on Inferno that fixes the issue with React.Children. It's live on the beta 42. The only work needed now is to add the NOOP callback on setState.

**Comment by mariusandra** [comment]
@degroote22 thank you for the work and a Merry Christmas! :)

I have published version `0.7.0-beta1`. 

If you have it installed, this will now work:

```js
// default for React
import Map from 'pigeon-maps'

// explicitly ask for React
import Map from 'pigeon-maps/react'

// explicitly ask for Inferno
import Map from 'pigeon-maps/inferno'

// choose React or Inferno if you have `BABEL_ENV` set
import Map from 'pigeon-maps/infact'
```

The same `/(react|inferno|infact)` works as well for `pigeon-overlay` version `0.2.0-beta1` and `pigeon-marker` versions `0.3.2` and up (they are under the beta tag, but no `-beta` in the version).

It's still under `-beta` because:

1) I want to get dead code elimination working for the bundles. Right now there are some `if (false) { require('react') } else { require('inferno') }` lines under the `lib/*` folders. While most people's webpack/rollup/etc setup will eliminate the dead code, we can't rely on this. So it's best to already create clean packages.

2) The map with inferno is jerky. The animation is smooth, but when you let go of the drag, it will jump for a frame.

This will be for after the holdays. Cheers!

**Comment by mariusandra** [comment]
I pushed out `0.7.0-beta2` that fixes problem nr 2 from above.

**Comment by degroote22** [comment]
That's awsome!! I'd like to help on number 1 but I know very little about it :(

**Comment by degroote22** [comment]
@mariusandra, have you ever used create-react-app?
The code comes with a lot of comments like `@on-eject-begin` and `@on-eject-end` and then it is eliminated [like so](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/scripts/eject.js#L76)
It's not too fancy but I guess it could do the job.

**Comment by mariusandra** [comment]
Hey, I got it working. I had to run babel twice, so it's not really elegant, but it does its job. Like so:

```json
{
    "build:lib:inferno": "BABEL_ENV=inferno ./node_modules/.bin/babel src --out-dir lib/inferno && ./node_modules/.bin/babel --no-babelrc --plugins minify-dead-code-elimination lib/inferno --out-dir lib/inferno",
    "build:lib:react": "BABEL_ENV=react ./node_modules/.bin/babel src --out-dir lib/react && ./node_modules/.bin/babel --no-babelrc --plugins minify-dead-code-elimination lib/react --out-dir lib/react"
}
```

`0.7.0-beta4` is out with the changes.

---

Before I'm ready to release 0.7.0, I still have a few issues to sort out:

1. The demo. Ideally I'd have a demo for both React and Inferno. I'll get on it after this ticket.
2. I'm calling a local plugin "./utils/babel-env-inline" in `.babelrc`. This should go into a separate npm package.

**Comment by mariusandra** [comment]
Those issues are resolved and `0.7.0` is out! Thanks guys for your help in getting this out!

@trueadm I understand with Inferno 1.0 you're building a new website with links to projects using inferno. Any chance to get this listed? Or maybe even the component running under a demo page?

**Comment by degroote22** [comment]
@mariusandra, this is already being discussed it with peope who are working on the new site [here](https://github.com/infernojs/inferno/issues/544).

**Comment by mariusandra** [comment]
@degroote22 Ah, great! Then I'll close this issue (default maps questions solved, inferno support solved) and reply in that thread.

Thanks again for making inferno support possible! 🥇
