### ISSUE TITLE
Debounce syncToProps so that onBoundsChange gets debounced

### ISSUE THREAD

**Issue by degroote22** [mariusandra/pigeon-maps#10]
This is quite simple to implement but I'd like to discuss the strategy.
Should we let the user set if he wants denouncing or not or should to user tell the time in ms to debounce (setting to 0 would turn debounce off)

@mariusandra, what's your opinion?

**Comment by mariusandra** [comment]
I think it should be configurable by the user. In fact, there are several constants at the top of the file that should probably be configurable:

```
const ANIMATION_TIME = 300
const DIAGONAL_THROW_TIME = 1500
const SCROLL_PIXELS_FOR_ZOOM_LEVEL = 150
const MIN_DRAG_FOR_THROW = 40
const CLICK_TOLERANCE = 2
const DOUBLE_CLICK_DELAY = 300
const DEBOUNCE_DELAY = 60
```

If we make the debounce delay configurable, sooner or later there will be someone who needs a bigger click tolerance or some other longer delay.

I'd ideally avoid having each of them as a separate `prop` and instead use just one `constants` or `options` prop.

However, we can cross that bridge when the time comes. The current 60ms delay works great for me!

**Comment by degroote22** [comment]
I definitively agree with you, one options props would be great.
60ms is fine for me too.
I'll try to think about scenarios where it would need to be changed but for now I think what we have is ok.
I'm closing the issue.
