### ISSUE TITLE
feature-request :  The credit links under the map should open new window

### ISSUE THREAD

**Issue by vasilevich** [mariusandra/pigeon-maps#101]
Hey, this plugin is great , and I find it very useful.
I have no problem whatsoever with it and I am glad to show credits right on the component/map.
But I believe the credit links of pigeon and openstreemap should use target="_blank" since if customers accidently click on it, their browser will go to an unrelated to the product page and this might confuse certain computer-illetirate people or/and lose all progress in certain websites.
![image](https://user-images.githubusercontent.com/1217224/86660848-c7e73d00-bff3-11ea-957c-963ebd37b3f5.png)

Imagine that you are in the middle of a purchase or post, and accidentally click the credit link, all the progress is lost or it can make other issues.

so this can be quite a major deal in certail websites.

Please consider it.
Thanks.

**Comment by vasilevich** [comment]
Please consider my pull request
https://github.com/mariusandra/pigeon-maps/pull/102

or implement it however you see fit.

**Comment by mariusandra** [comment]
Hey! Thanks for the PR! I was in the middle of converting the codebase to typescript... and it would have been complicated to merge this in, so I had to close it. But I did implement this! It'll be out with the next release once I test that the TS code works well enough.

**Comment by mariusandra** [comment]
This is now out in `v0.16.0`

**Comment by vasilevich** [comment]
Thank you!
