### ISSUE TITLE
Map is in black and white.

### ISSUE THREAD

**Issue by DaOneRom** [mariusandra/pigeon-maps#108]
Does someone know the right API on how can I make it with colors?

![image](https://user-images.githubusercontent.com/65810365/89629358-44f62280-d8d0-11ea-96b3-d03edea92e5c.png)

**Comment by vasilevich** [comment]
Hey,  you get black and white because that is the default tile provider,
to fix that you need to provide another tile provider,
here is an example of a colorful one:
```

function mapTilerProvider(x, y, z, dpr) {
  return `https://c.tile.openstreetmap.org/${z}/${x}/${y}.png`;    //<--- tile provider url, should provide colorful map from openstreet
}

  <Map
      provider={mapTilerProvider}  // <---- TILE PROVIDER  put what you want
      defaultCenter={[34.951038, 39.890073]}
      defaultZoom={18}
      height={150}
      width={230}
    >

   </Map>
```
