### ISSUE TITLE
Zoom-Buttons + and -

### ISSUE THREAD

**Issue by xstable** [mariusandra/pigeon-maps#113]
Would be great to have an Zoom-Button Panel.
This way we can deactivate Mouse-Action on Map, but keep the possibility to zoom.

Zoom-Images should be svg's to keep the footprint low.

![image](https://user-images.githubusercontent.com/1778068/92614699-a38e3200-f2bc-11ea-9cab-2717aa1a95a2.png)

**Comment by mariusandra** [comment]
Version `0.18.0` now exports a `<ZoomControl />` component that does just that:

![image](https://user-images.githubusercontent.com/53387/111443386-9dfd2300-8709-11eb-8d23-1da516d8077c.png)

**Comment by xstable** [comment]
Nice.
