### ISSUE TITLE
Wikimedia-Maps didn't work in the demo

### ISSUE THREAD

**Issue by xstable** [mariusandra/pigeon-maps#116]
Got 403 error (forbidden) for map-tiles https://pigeon-maps.js.org/
![image](https://user-images.githubusercontent.com/1778068/97069875-8777f300-15d3-11eb-815b-69edfe164775.png)

**Comment by mariusandra** [comment]
Thank you! The maps will be removed as soon as [this pr](https://github.com/js-org/js.org/pull/4862) is merged and [the docs ](https://github.com/mariusandra/pigeon-maps-website) move over to netlify.

**Comment by maooricio** [comment]
Hi, in order to make this works we have to uninstall and install the module again? In advance thanks.

**Comment by Alecell** [comment]
I'm getting that 403 error on my website, what happened? I need to update the package?

**Comment by mariusandra** [comment]
Wikimedia closed the tap for us to use their maps. The new default map in the demo is just the regular OSM map. Please update the library if you're having the issue.
