### ISSUE TITLE
Module has no exported member 'Marker'

### ISSUE THREAD

**Issue by johannesaxner-valtech** [mariusandra/pigeon-maps#121]
I just added pigeon-maps 0.17 to my typescript react project and I can't build due to the package not exporting Marker or Overlay components. I get errors like this: 

> Module '"../../../node_modules/pigeon-maps/lib"' has no exported member 'Marker'.

> Module '"../../../node_modules/pigeon-maps/lib"' has no exported member 'Overlay'.

Is this a faulty type definition or something wrong in my end?

**Comment by GeorgiHalembakovv** [comment]
I have the same issue with Marker and Map.

**Comment by mariusandra** [comment]
Hey! Indeed while the JS code itself was there, the TS types were generated into a different folder. 

Please let me know if `0.17.1` works.
