### ISSUE TITLE
Draggable onDragMove is returning wrong coordinates.

### ISSUE THREAD

**Issue by hurelhuyag** [mariusandra/pigeon-maps#137]
I'm trying to implement a polygon editor in pigeon-maps. I assuming onDragMove is reporting wrong coordinates. If I'm wrong. Can you show me the correct example?

Here is my example: [https://codesandbox.io/s/pigeon-maps-dragmove-1riru?file=/src/App.js](https://codesandbox.io/s/pigeon-maps-dragmove-1riru?file=/src/App.js)

In this example, polygon edges have a draggable circle. When the draggable circle moves around, Polygon should resize accordingly.

**Comment by mariusandra** [comment]
Hey, this was indeed broken. 
It will if you upgrade to pigeon-maps `0.19.7` :)

**Comment by hurelhuyag** [comment]
Thank you. Now it is working as expected.
