### ISSUE TITLE
Mapbox term of service

### ISSUE THREAD

**Issue by istarkov** [mariusandra/pigeon-maps#14]
At first wanna say wow!!! It's how google map must work.

BTW what about tiles services, looks like the nice looking tiles from MapBox is prohibited to use:

Here https://www.mapbox.com/tos/#[TMAmYmaa] 

_You must access and use map tiles, static map images, style files, glyphs, and sprites hosted by Mapbox (collectively "Map Assets”) only through our APIs._

Other choices like OSM tiles looks really bad. 

So is any plan at mapbox exists to allow their tiles usage?

**Comment by mariusandra** [comment]
Hey,

First, thank you! :)

Second, reading from this page: https://www.mapbox.com/api-documentation/#maps

> If you use Mapbox.js, Mapbox GL JS, or another library like Leaflet, you're already using this API.

So I think we're good. 

There's another problem. Mapbox limits free accounts to 50k map views/month (and is very restrictive about what you can build if you pay them). For the last 7 days I had 16k map views on the demo page. I'm not sure how traffic will go, but like this 50k/month is not enough. And I don't want to pay 500€/month for this :)

Thus an alternative is badly needed.

I do like the tiles of Wikipedia (the button "wikimedia" on the demo page). They look close enough to Google Maps that many users probably won't see the difference. The drawback: they're slow and can't be used directly. They do however provide all the code: https://github.com/kartotherian/kartotherian/

Ideally someone should create an easily-installable, self-hosted and self-upgrading version of those maps. There are [some guides](https://switch2osm.org/serving-tiles/building-a-tile-server-from-packages/) on https://switch2osm.org/ , but there's nothing as easy as:

1. Get a server.
2. apt-get install X or docker run tileserver-xyz
3. no step 3

Any ideas?

Is anyone willing to work on such a project? :)
