### ISSUE TITLE
Mapping custom JSON to anchor JSX attribute

### ISSUE THREAD

**Issue by mk53202** [mariusandra/pigeon-maps#143]
I'm stuck trying to map customer JSON to the anchor. My JSON looks like this:

[{"event_id":"76341710-cfff-450c","event_time":"2021-10-22T16:58:19.624699","location":{"latitude":"44.044035667","longitude":"-88.954343833"}}]

The map function I'm using is: 
```
    const PigeonMarkers = items.map((marker, index) => (
      <Marker
        key={index}
        anchor={[marker.location['latitude'] + ',' + marker.location['longitude']]}
        payload={marker.event_id}
        onClick={this.onMarkerClick}
      />

    ));
```

Not working, any idea how to do this? I'm super stumped how to fill in the anchor with the data I have.

**Comment by mariusandra** [comment]
Hey, the `anchor` expects an array with numbers, not strings of numbers surrounded by quote symbols :).
