### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by amiiit** [mariusandra/pigeon-maps#15]
Hello and great work!

What I'm missing in order to integrate into my app is clustering of markers. Are there any thoughts about how to implement this? I didn't dig into the code in depth yet but I would gladly give it a shot if you also think this is a viable feature. Any idea where I could begin to implement this?

**Comment by mariusandra** [comment]
Hey!

Such a plugin would be great to have! I even joked about the name here: https://twitter.com/mariusandra/status/811255900451311616

Assuming that the API is something like this:

```js
<Map>
  <Cluster {...someProps}>
    <Marker anchor={[lat, lng]} />
    <OtherOverlay anchor={[lat, lng]} />
  </Cluster>

  <OutsideMarker anchor={[lat, lng]} />
</Map>
```

There are just a few things that need to be done:

1. Create an algorithm, which for a given zoom level and array of marker coordinates calculates the clusters.

2. In `<Cluster />`, take all the children and run them through the algorithm in the point above (similar to [this](https://github.com/mariusandra/pigeon-maps/blob/4501ca18b2a4acacb6632e5872ccfb3b468a879a/src/index.js#L773)) and then either render them or instead render a cluster element. Pass to the rendered children and cluster elements the same `top`, `left`, `latLngToPixel` and `pixelToLatLng` vars.

3. Optimise the code so the clustering calculations only take place when the children or the zoom level change.

The hardest part IMO is point nr 1. For ideas how to tackle it, I'd look at how other projects have done it:
- https://github.com/Leaflet/Leaflet.markercluster
- https://github.com/PaulLeCam/react-leaflet/issues/37 and https://github.com/troutowicz/geoshare/blob/master/app/components/MarkerCluster.jsx
- https://github.com/googlemaps/js-marker-clusterer

You might look into Quadtrees to find a way to quickly divide the space between markers:
- https://en.wikipedia.org/wiki/Quadtree
- http://www.mikechambers.com/blog/2011/03/21/javascript-quadtree-implementation/
- https://github.com/timohausmann/quadtree-js
... the benefit with them is that you won't have to recalculate the clusters manually when the zoom level changes. Plus it's fast to move points between nodes in the tree when a coordinate changes. The drawback is that the clusters will be aligned to a grid and look "boxy".

Perhaps also look at code samples for different K-Means Clustering libraries, e.g.:
- https://github.com/NathanEpstein/clusters
... although that's probably way too slow for this use case.

So there are many ideas to explore. Good luck! :)

**Comment by amitit** [comment]
Great, that's the kind of answer I was hoping for. I will look into it the following days

**Comment by degroote22** [comment]
@mariusandra this is a great lib for clustering. it's really fast! https://github.com/istarkov/supercluster
i've been using it with pigeon-maps almost out of the box (it expects nw and se bounds, and pigeon-maps gives sw and ne.)

but this does the job:

```
const converter= ({bounds, center, zoom}) =>
({
  bounds: {
    nw: {
      lat: bounds.ne[0],
      lng: bounds.sw[1]
    },
    se: {
      lat: bounds.sw[0],
      lng: bounds.ne[1]
    }
  } 
})
```

**Comment by amiiit** [comment]
@degroote22 this is great, having a lib that does the hard work for us. I would start with that and optimize on bundle-size or performance later if necessary.

Without cluttering the API I see two options of passing down a reference so that `<Cluster>` will know the map bounds

1. Pigeon will set some metadata to the context (I believe InfernoJS is also supporting context). It seems to me that this has a big **pro** on performance but maybe a **contra** on best practices. What do you think? Is this okay to use context to implement a library?

2. As done by [react-leaflet](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Map.js#L147), clone all children of `<Map>` and set a prop `map` or similar containing the necessary metadata.

__Example from react-leaflet:__

```
render (): React.Element<*> {
    const map = this.leafletElement
    const children = map ? React.Children.map(this.props.children, child => {
      return child ? React.cloneElement(child, {map, layerContainer: map}) : null
    }) : null

    return (
      <div>
        {children}
      </div>
    )
```

Do you have other ideas or thoughts on the above?

**Comment by degroote22** [comment]
I didn't get what you meant on your second question, but talking about question 1, Inferno supports context just like React but you don't have to set contextTypes to make it work, it's already there on this.context on every children.
With that being said, it's completely fine to use it IF the user has no idea that that is happening. The point is that if the context api changes, the user shouldn't need to care about it.

Also, the lib I said up there works great out of the box if you have static data. In my case where data is being downloaded on the fly and numbers can get quite big, I've found it better to firstly check all the point to see wich are within the bounds, then I cluster them.

And talking about bundle size,[ the actual lib ](https://github.com/istarkov/supercluster) is quite small per se but it uses a [r-tree lib to do the heavy work.](https://github.com/mourner/rbush)

Read the source code of supercluster (couple files 100 lines long) if you have the time to see what i'm talking about.

I'll thought about the api to implement this aswell. On my project I do clustering before creating the children, but of course there are more elegant/easier implementations.

Also, I've designed a little cluster component that is really nice. It could be used here if you're interested. [It's live here, check it out. Zoom out to see how it behaves with 50 items clustered, for instance](https://teste-firebase-822c4.firebaseapp.com/busca/-19.5815631/-42.647519999999986) -- don't mind this website performance or bugs, it was only being used to track an Inferno bug on some old version of the website I'm working with.

**Comment by mariusandra** [comment]
@amiiit Regarding cloning + props vs context, I prefer a consistent API. We already pass several props to the children (`left`, `top`, `latLngToPixel` and `pixelToLatLng`), so adding `bounds` and `zoom` there seems like the better way.

In fact, I released `0.8.0` that includes those two and in addition `center`, `width` and `height` in a new prop `mapState`. 

You can see them in action here: https://youtu.be/uLsweogEg0o

The code behind it is:

```js
class Cluster extends Component {
  render () {
    const { width, height, zoom, bounds } = this.props.mapState
    return (
      <div style={{ width, height }}>
        {zoom},
        {[...bounds.ne, ...bounds.sw].map(b => Math.round(b * 1000) / 1000).join(',')}
      </div>
    )
  }
}
```

and then

```js
        <Map ...>
          <Marker ... />
          <Marker ... />
          <Cluster /> (no props given)
        </Map>
```

The `mapState` updates at every animation frame, while the center and zoom displayed below the map update just when the animation stops.

**Comment by amiiit** [comment]
Short update: I've released [`pigeon-cluster`](https://www.npmjs.com/package/pigeon-cluster) on npm. It's _usable_ but I'm going to revisit the whole code again to address performance issues. This is just a first sketch. I hope to have better results during next week.

[Here is an example on how to use it ](https://github.com/amiiit/pigeon-cluster/blob/master/demo/demo.js)

[Here is a live example on my side-project](https://parking.spots.pw/), you can see that with ~4k markers it starts to get cranky.

**Comment by mariusandra** [comment]
Hey, very cool! :)

Keep us posted!

**Comment by amiiit** [comment]
https://github.com/amiiit/pigeon-cluster

See above for documentation and example but in a nutshell:

```
import Map from 'pigeon-maps'
import Cluster from 'pigeon-cluster'
import Marker from 'pigeon-marker'

const coordinates = [
    [lat,lng],
    [lat,lng],
    [lat,lng]
    ...
]

<Map center={[50.879, 4.6997]}
     zoom={4}
     width={600}
     height={400}>
    <Cluster>
        {
            coordinates.map(coordinate => <Marker key={coordinate.toString()} anchor={coordinate} payload={1}/>)
        }
    </Cluster>
</Map>
```
