### ISSUE TITLE
GeoJson TypeError: latLngToPixel is not a function

### ISSUE THREAD

**Issue by djeka07** [mariusandra/pigeon-maps#174]
First want to say that i love this library, switching from mapbox for performance reasons and already seeing massive performance gains.

I have a problem with GeoJson though. I get an error that latLngToPixel is not a funcion and in the source code, i dont see it being sent from the MultiLineString component to the LineString component.

MultiLineString component looks like this:

```
export function MultiLineString(props: GeometryProps): JSX.Element {
  return (
    <>
      {props.coordinates.map((line, i) => (
        <LineString coordinates={line} key={i} />
      ))}
    </>
  )
}
```

And the LineString component deconstruct the latLngToPixel from props:

```
export function LineString(props: GeometryProps): JSX.Element {
  const { latLngToPixel } = props
  const p =
    'M' +
    (props.coordinates as Array<[number, number]>).reduce((a, [y, x]) => {
      const [v, w] = latLngToPixel([x, y])
      return a + ' ' + v + ' ' + w
    }, '')

  return <path d={p} {...(props.svgAttributes as SVGProps<SVGPathElement>)} />
}
```

The MultiPolygon component for example spreads props and therefore the Polygon gets the latLngToPixel props.

```
export function MultiPolygon(props: GeometryProps): JSX.Element {
  return (
    <>
      {props.coordinates.map((polygon, i) => (
        <Polygon {...props} coordinates={polygon} key={i} />
      ))}
    </>
  )
}
```

Am i missing something or is this a bug?

Thanks in advance!

//André

**Comment by mariusandra** [comment]
Out with v0.21.5
