### ISSUE TITLE
Prevent window scrolling when scrolling within the map

### ISSUE THREAD

**Issue by knoopx** [mariusandra/pigeon-maps#2]
This occurs on chrome/android when panning over the map, the window also scrolls.

**Comment by mariusandra** [comment]
Hey, I was developing on Chrome/Android and everything works great for me.
What versions are you using? Any chance to post a video or something like that?

**Comment by knoopx** [comment]
It happens on the live demo page

**Comment by degroote22** [comment]
Tried it out here on a Galaxy J1, android(duh) and chrome. It works ok...
Even with extreme zoom on the page in won't move neither vertically nor horizontally.

**Comment by mariusandra** [comment]
Can anyone reproduce it? Any issues with other browsers?

**Comment by knoopx** [comment]
![demo](https://cloud.githubusercontent.com/assets/100993/21382038/de28ff86-c75e-11e6-888f-6f5f19b6b8b3.gif)

**Comment by mpontus** [comment]
There's also an issue with pinch zooming on mobile devices, which zooms web page instead of the map.

To fix those problems you can wrap `PigeonMap` with an element with `touch-action: none` CSS property.

**Comment by mariusandra** [comment]
Hey, this is fixed in `v0.10`
