### ISSUE TITLE
Use local map image?

### ISSUE THREAD

**Issue by Seb-AS** [mariusandra/pigeon-maps#29]
It's possible to use a regular jpg/png as the provider? 
I need to show maps for each floor of a building.(No tiles needed)
Thanks

**Comment by mariusandra** [comment]
Hey, unfortunately not. There may be other libraries available for this purpose though. `pigeon-maps` does expect a spherical mercator projection and calculates all coordinates accordingly. Adding regular png/jpg support will be a too big departure from the original goals of this project.
