### ISSUE TITLE
Feature request: read-only/disabled map

### ISSUE THREAD

**Issue by ccMatrix** [mariusandra/pigeon-maps#30]
When a user has picked a certain location we just want to show him the information on the map in his profile. This map should be not movable/clickable/zoomable. It can be unlocked when an edit button is clicked.

Right now we wrap/override the handlers for mouse and touch and wheel events and disable them if we have a readonly flag in our wrapping component.  It works but is ugly because it overrides internal methods of pigeon map.

Therefore I request the feature to add an optional prop readonly or disabled which, if set, will just make the component show whatever coordinate is provided with whatever zoom level is set but disables any mouse/touch and wheel methods.

**Comment by mariusandra** [comment]
Hey, this is now possible with `v0.10` by setting the `mouseEvents` and `touchEvents` props to `false`
