### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by tananaev** [mariusandra/pigeon-maps#31]
Is there any plan to implement features like circles, polylines and polygons? In other issues I saw you mentioned that you might look into it at some point.

We at [Traccar project](https://github.com/traccar/traccar) are looking into re-writing our web app using React and it would be awesome to have a native React map library, but we actually need some more advanced functionality.

**Comment by mariusandra** [comment]
Hey, the the moment in my own project, this need hasn't surfaced... however it shouldn't be too hard to implement. Each [overlay](https://github.com/mariusandra/pigeon-maps#overlays) gets the `latLngToPixel` function and other data about the map, so you can just create a SVG line or other object accordingly.

Here's a super simple example for drawing a line between any number of points:

```jsx
const Line = ({ mapState: { width, height }, latLngToPixel, coordsArray, style = { stroke: 'rgb(255,0,0)', strokeWidth: 2 } }) => {
  if (coordsArray.length < 2) {
    return null
  }

  let lines = []
  let pixel = latLngToPixel(coordsArray[0])

  for (let i = 1; i < coordsArray.length; i++) {
    let pixel2 = latLngToPixel(coordsArray[i])
    lines.push(<line key={i} x1={pixel[0]} y1={pixel[1]} x2={pixel2[0]} y2={pixel2[1]} style={style} />)
    pixel = pixel2
  }

  return (
    <svg width={width} height={height} style={{ top: 0, left: 0 }}>
      {lines}
    </svg>
  )
}
```

and then put this in the `<Map>` in the demo:

```jsx
<Line coordsArray={[markers.leuven1[0], markers.leuven2[0]]} />
```

This works, but is not as buttery smooth as I would have liked, at least on my development build. In a real fully functional line component you would do more than just draw it like this, e.g. to not draw anything outside the map, use `transform` and `willChange` to make translations faster when the zoom level is constant, etc.

But it's a start :).

**Comment by vanakenm** [comment]
Could use anything supported by SVG here such as polygon, right (and possibly fill attribute) ?

**Comment by mariusandra** [comment]
@vanakenm yes of course

**Comment by vijay122** [comment]
@mariusandra hi, can you tell me how the overlay wraps the line with small example.
i am not able to make the latLngToPixel calculation.

**Comment by Southclaws** [comment]
Sorry to revive a zombie post but I'm just wondering if there's a quick way to calculate a radius for an svg circle where I know the kilometers/miles.

I could probably figure out the maths for this, if I know the range from the given zoom value, but is there a function for this or some math I can look at in the code?

Thanks!

**Comment by mariusandra** [comment]
Hey, no quick way that I know of. You'll have to basically calculate a bunch of coordinates in a circle around a coordinate, and then use the new GeoJSON utils to plot them on the map: https://pigeon-maps.js.org/docs/geo-json-loader

Ideally this could be integrated into pigeon maps's GeoJSON utils as well, but it's not there yet :).

**Comment by Lir-kulikov** [comment]
> Hey, the the moment in my own project, this need hasn't surfaced... however it shouldn't be too hard to implement. Each [overlay](https://github.com/mariusandra/pigeon-maps#overlays) gets the `latLngToPixel` function and other data about the map, so you can just create a SVG line or other object accordingly.
> 
> Here's a super simple example for drawing a line between any number of points:
> 
> ```js
> const Line = ({ mapState: { width, height }, latLngToPixel, coordsArray, style = { stroke: 'rgb(255,0,0)', strokeWidth: 2 } }) => {
>   if (coordsArray.length < 2) {
>     return null
>   }
> 
>   let lines = []
>   let pixel = latLngToPixel(coordsArray[0])
> 
>   for (let i = 1; i < coordsArray.length; i++) {
>     let pixel2 = latLngToPixel(coordsArray[i])
>     lines.push(<line key={i} x1={pixel[0]} y1={pixel[1]} x2={pixel2[0]} y2={pixel2[1]} style={style} />)
>     pixel = pixel2
>   }
> 
>   return (
>     <svg width={width} height={height} style={{ top: 0, left: 0 }}>
>       {lines}
>     </svg>
>   )
> }
> ```
> 
> and then put this in the `<Map>` in the demo:
> 
> ```js
> <Line coordsArray={[markers.leuven1[0], markers.leuven2[0]]} />
> ```
> 
> <img alt="screen shot 2018-09-11 at 10 53 18" width="658" src="https://user-images.githubusercontent.com/53387/45352682-f68b5c80-b5b0-11e8-8286-fe9e89372bc6.png">
> 
> This works, but is not as buttery smooth as I would have liked, at least on my development build. In a real fully functional line component you would do more than just draw it like this, e.g. to not draw anything outside the map, use `transform` and `willChange` to make translations faster when the zoom level is constant, etc.
> 
> But it's a start :).

Hello! Where i can see logic inside latLngToPixel()?

**Comment by Lir-kulikov** [comment]
@mariusandra, Hello! How to pass latLngToPixel prop to Line Component? Where can i get this func?

**Comment by vladiyudi** [comment]
Thanks for the code. I applied it ot me app and it works perfectly with a single line, but when I try to draw several lines, it doesn't work. Im able to draw just one line. Do you have a advice how to apply this code for several lines situation?

**Comment by bepitulaz** [comment]
Sorry, for making this post up again. I just want to put my implementation here for `latLngToPixel` function, in case anyone need it. It's straightforward.

```
/**
 * Converts latitude and longitude coordinates to pixel coordinates.
 *
 * @param {number[]} coordinate - The latitude and longitude coordinates in the format [lat, lng].
 * @param {{ ne: number[], sw: number[] }} bounds - The northeast and southwest bounds of the map in the format { ne: [lat, lng], sw: [lat, lng] }.
 * @param {{ width: number, height: number }} mapSize - The width and height of the map in pixels in the format { width, height }.
 * @returns {number[]} The pixel coordinates in the format [x, y].
 */
function latLngToPixel(coordinate, bounds, mapSize) {
  const [lat, lng] = coordinate
  const { ne, sw } = bounds
  const { width, height } = mapSize

  const x = ((lng - sw[1]) / (ne[1] - sw[1])) * width
  const y = ((ne[0] - lat) / (ne[0] - sw[0])) * height

  return [x, y]
}
```

Then you can use it inside `Line` function written by @mariusandra 🙂

<img width="1270" alt="image" src="https://github.com/mariusandra/pigeon-maps/assets/313962/a4ae6652-51f3-4001-afe0-f1cbfd1d08bf">
