### ISSUE TITLE
Does not seem to work with inferno

### ISSUE THREAD

**Issue by geritol** [mariusandra/pigeon-maps#39]
I have tried to add pigeon maps to an inferno project created with `npx create-inferno-app` (inferno version `5.6.1`), and getting the following error.

![kepernyofoto 2018-09-18 - 12 42 34](https://user-images.githubusercontent.com/5496681/45682479-a415e700-bb40-11e8-9350-ae97b7807b88.png)

```TypeError: Super expression must either be null or a function, not object
_inherits
node_modules/pigeon-maps/lib/inferno/index.js:63
  60 | 
  61 | function _inherits(subClass, superClass) {
  62 |   if (typeof superClass !== "function" && superClass !== null) {
> 63 |     throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
  64 |   }subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } });if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;
  65 | }
  66 | 
View compiled```

**Comment by mariusandra** [comment]
Hi, since 0.12.0 I have removed inferno support. My apologies to anyone affected, but bundling a broken unused feature that adds maintenance complexity for uncertain gains, seemed like a losing strategy. Please use the react version with inferno-compat from now on.
