### ISSUE TITLE
Support width="100%" and height="100%" out of the box

### ISSUE THREAD

**Issue by mariusandra** [mariusandra/pigeon-maps#4]
Currently the map needs width={number} and height={number} props to work.

To make it 100% width, you need to wrap it with a component that measures and passes the width and the height... and also responds to onresize and other events.

It should be easier than that.

If width="100%" is passed, it should then be possible to pass a default width/height for server side rendering.

**Comment by degroote22** [comment]
Take a look at [react-sizeme](https://github.com/ctrlplusb/react-sizeme) and the choices they made.
On the server they don't render the content at all. Since it'd be rendered wrongly, you save server resources and bandwith only rendering the right stuff.

**Comment by mariusandra** [comment]
Will do, thanks.

I do want to allow for the possibility to render content on the server though.

In my app, I know the final width and height of the map before rendering with about 90% certainty... and when I don't, there's just a small margin of error.

**Comment by PlanetIrata** [comment]
Hi, thanks for great works, but I also miss the ability to set the width  at 100% of the container, which is an absolute need for designing any website nowadays: responsive design require some elements (like a map aside a contact form) to be 50% width on wide screen and 100% width on a mobile screen.

Do you think you'll add this feature soon or have you a workaround ?

**Comment by mariusandra** [comment]
Hi, I have used [react-dimensions](https://github.com/digidem/react-dimensions) for this purpose.

**Comment by mariusandra** [comment]
100% width and height are now supported with `v0.10`. It also auto updates if the window is resized, but not if the component changes size in any other way (e.g. some dom node is resized). Please wrap it with some other librarly like [react-sizeme](https://github.com/ctrlplusb/react-sizeme) if you need this support.

**Comment by alexalv** [comment]
I am using v0.10.4 and trying to pass width="100%" and height="100%" props and currently getting 100% x 100% grey div as a result. There are some warnings in console: 

> index.js:2178 Warning: Failed prop type: Invalid prop `width` of type `string` supplied to `Map`, expected `number`.
    in Map (at Map.js:10)
    ...
index.js:2178 Warning: Failed prop type: Invalid prop `height` of type `string` supplied to `Map`, expected `number`.
    in Map (at Map.js:10)
    ...
index.js:2178 Warning: `NaN` is an invalid value for the `width` css style property.
    in div (created by Map)
    ...

**Comment by mariusandra** [comment]
Hey, pass nothing for width and height and it'll default to 100%

**Comment by alexalv** [comment]
Oh, works perfectly! Thank you very much!

**Comment by meepeek** [comment]
width / height 100% works fine in chrome (Mac) but render grey in safari (Mac), safari iOS, chrome iOS until refresh. This happen every time on new tab. Any suggestion how to fix it ?

**Comment by bigbn** [comment]
If somebody got no luck with sizeMe try to use `AutoSizer` from `react-virtualized`. It does magic in my situation, which `sizeMe` can't.
![image](https://user-images.githubusercontent.com/740864/75672628-93a4ee00-5c9a-11ea-9124-09d695e338db.png)
