### ISSUE TITLE
Map title bearing

### ISSUE THREAD

**Issue by raja** [mariusandra/pigeon-maps#42]
Would it be possible to support setting a bearing?

https://www.mapbox.com/mapbox-gl-js/example/set-perspective/
https://www.mapbox.com/help/define-bearing/

**Comment by mariusandra** [comment]
Sorry, that's not possible. `pigeon-maps` is 2D only and doesn't work with rich vector layers like MapBox GL. Thus adding something like this will greatly increase the code size and will look bad in the end anyway. For example all text will be at an angle as well, as it's just part of the tile.
