### ISSUE TITLE
Marker

### ISSUE THREAD

**Issue by ioterateam** [mariusandra/pigeon-maps#44]
How to change icon marker? and how to show tooltip if marker onClick?

**Comment by mariusandra** [comment]
Hi, the point is that you make your own. Here's an example for putting any DIV on a map... and for making a specialised marker div:

```js
const DivMarker = ({ left, top, style, children }) => (
  <div style={{
    position: 'absolute',
    left: left,
    top: top,
    ...(style || {})
  }}>{children}</div>
)

const YellowMarker = ({ left, top, style, children }) => (
  <div style={{
    position: 'absolute',
    left: left - 15,
    top: top - 30,
    width: 30,
    height: 30,
    borderBottomLeftRadius: '100%',
    borderBottomRightRadius: '100%',
    background: 'yellow',
    ...(style || {})
  }}>{children}</div>
)

render(
  <Map ...>
    <DivMarker
      anchor={[50.879, 4.6997]}
      offset={[15, 30]}
      style={{
        width: 30,
        height: 30,
        background: 'red',
        borderBottomLeftRadius: '100%',
        borderBottomRightRadius: '100%'
      }}>
      o
    </DivMarker>

    <YellowMarker anchor={[50.874, 4.6947]}>
      o
    </YellowMarker>
  </Map>
)
```

<img width="628" alt="screenshot 2018-10-11 at 00 11 19" src="https://user-images.githubusercontent.com/53387/46768886-38abd900-ccea-11e8-9849-b5945ea71a41.png">

As for tooltips and info windows - you render them like you would render markers, just point the other way.

**Comment by alicerocheman** [comment]
Hello @mariusandra 

Thank you for the examples, however I'm working with Typescript and I get an error when I use your example:

```
<DivMarker anchor={establishmentCenter}>Hello World!</DivMarker>
```
error: Property 'anchor' does not exist on type 'IntrinsicAttributes & { left: any; top: any; style: any; children: any; }'

I thought to use the MarkerProps interface but it's not exported :/
