### ISSUE TITLE
Min map area

### ISSUE THREAD

**Issue by fmturati** [mariusandra/pigeon-maps#45]
Hi, I'd like to say thanks for sharing this plugin and ask if you know some way to restrict the position when the map is min zoom.. here is a example:
![sketch](https://user-images.githubusercontent.com/37228377/47109512-4807b680-d203-11e8-933f-13a7b400e205.png)

thank you so much

**Comment by mariusandra** [comment]
Hey! This is tricky to get right, but I gave it a shot. In `v0.11.4` there is now a hidden prop called `limitBounds`. It defaults to `"center"`, which retains the current behaviour. If, however, you set it to `"edge"`, then the gray area will not be shown and the map will try to cover as much of the screen as possible.

It's still beta and has one obvious flaw: you can temporarily drag the map and reveal the gray area... and it'll then snap back... much like it currently snaps if you drag the map even further away.

I'll try to get that done before `0.12`, but I can't promise when that will be. It could be days... or could be weeks. Thanks for being patient :).

**Comment by fmturati** [comment]
That's great! Thanks for helping me... I'll try to do that... good job!
