### ISSUE TITLE
Use [of pigeon-marker] with Webpack seems to assume image loaders

### ISSUE THREAD

**Issue by atombender** [mariusandra/pigeon-maps#49]
When attempting to bundle an app using Webpack, it will fail with an error such as this:

```
Uncaught Error: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
```

This is because of the use of image imports such as `import pin from './img/pin.png'`. If the consumer app doesn't have a loader for this installed, it appears that loading the `pigeon-marker` bundle fails.

This implies that the bundle `lib/react/infact.js` is not self-contained — it relies on a runtime whose `require()` implements image loading. I don't know enough about Webpack to say whether this is intentional, but it seems suspect to me. Surely the bundle on your end should be self-contained, and shouldn't rely on which loaders have been installed in the app that uses it. Whatever Webpack spits out on your end should already be embedding the images.

**Comment by mariusandra** [comment]
Hi, yes, the `pigeon-marker` package is a sample project that imports an image. Please use pigeon-overlay instead or roll your own.
