### ISSUE TITLE
without yarn dependency 

### ISSUE THREAD

**Issue by chintan9** [mariusandra/pigeon-maps#5]
without yarn dependency

**Comment by mariusandra** [comment]
`pigeon-maps` is not dependent on yarn.

Can you clarify?

**Comment by chintan9** [comment]
how can I install without `yarn`

**Comment by mariusandra** [comment]
Hey, then as with any other `npm` package:

```
npm install --save pigeon-maps
```

**Comment by mariusandra** [comment]
I added it to the readme as well.
