### ISSUE TITLE
Why do the demo markers point to Belgian cities?

### ISSUE THREAD

**Issue by jorgeobsidian** [mariusandra/pigeon-maps#51]
Just curious

**Comment by adamhammes** [comment]
Looking at the [author's profile] suggests that he is Belgian. Probably chose cities he knew.

**Comment by mariusandra** [comment]
I live there, no other reason. 
(but I'm not Belgian...)

**Comment by jorgeobsidian** [comment]
Cool, I was curious since I travel to Belgium frequently
