### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by hermanbanken** [mariusandra/pigeon-maps#52]
Feature request: I'd love to be able to specify a rotation.

I've looked into building a PR for this, but it is quite complex. I think changing only adding rotation to the tile transform and adjusting pixelToLatLng & latLngToPixel wouldn't work, because there is also stuff like interactions and bounds that need to be updated. I might work on this myself, but if you have any ideas, please tell :)

**Comment by mariusandra** [comment]
Hey, this is indeed quite complex I'm afraid. The current codebase has been written without this requirement in mind and is optimised to be as compact as reasonably possible. Thus extending it to support rotation (or perspective as asked in #42) is not an easy task... and the changes will probably add a lot of code that will go unused for 99+% of people. I would prefer to keep the core of pigeon-maps as light as possible.

Other than not doing it, I'm not sure what's a good path forward :)
