### ISSUE TITLE
SSR-mismatch for map-images when client has high DPR

### ISSUE THREAD

**Issue by romandecker** [mariusandra/pigeon-maps#59]
First of all, thanks for this awesome map!

We've run into a small problem: When server-side rendering a map, the server doesn't know about the client's device-pixel-ratio, so it just renders with the default map images.

When that server-rendered map is then hydrated on a client with a higher device-pixel-ratio however, pigeon-maps will choose a different version of the images, leading a react warning like this:

![Screen Shot 2019-05-09 at 10 12 09](https://user-images.githubusercontent.com/439587/57437850-efe9dd80-7242-11e9-951e-a3ba3f8f6c6c.png)

```
index.js:1 Warning: Prop `src` did not match. Server: "https://maps.wikimedia.org/osm-intl/15/17180/10548.png" Client: "https://maps.wikimedia.org/osm-intl/15/17180/10548@2x.png"
```

Any ideas on how to best solve this problem?

**Comment by mariusandra** [comment]
Hey, I hope `0.13.0` fixes the problem :).
