### ISSUE TITLE
layers=T

### ISSUE THREAD

**Issue by vijay122** [mariusandra/pigeon-maps#60]
this is not an issue, may be a new ask. map loads local language in places like thailand, china and russia. Openstreetmap provides feature to give both local language and english language.
https://www.openstreetmap.org/#map=3/-12.90/109.78&layers=T

if this option can be passed as a prop to the map, it would be helpful.

**Comment by bonesoul** [comment]
i also wonder this if possible?

**Comment by mariusandra** [comment]
This depends on the layer you use for the map, and the provider of that layer. Some of the support locale params, some don't. Nothing pigeon-maps can do here.
