### ISSUE TITLE
Can this be used in React Native app?

### ISSUE THREAD

**Issue by msaharia** [mariusandra/pigeon-maps#64]
Hi - this library is simply perfect. And I will be using it for a Web display.

I was wondering if it can be used with React Native for super fast (but simple) displays inside apps? Could you please direct me towards any relevant information?

**Comment by mariusandra** [comment]
Hi, unfortunately it doesn't work with React Native. All the map tiles are rendered as absolutely positioned and scaled `<div/>`s and that won't work with React Native, as each platform has its own rendering primitives. Someone could probably fork it and make it work, but it won't be me, sorry :).
