### ISSUE TITLE
TileLayers

### ISSUE THREAD

**Issue by porfirioribeiro** [mariusandra/pigeon-maps#66]
Hi, first of all i want to say thank's for your work.
Having a full react map api is so nice

Would be nice to split the TileLayer functionality from Map so we could use different layers on top of each other.

**Comment by zdila** [comment]
Missing overlay layers is also a blocker for us to migrate our project from react-leaflet. Also an abstraction as Leaflet's `GridLayer` would be nice to eg. render tiles as `canvas` elements.
