### ISSUE TITLE
Geojson overlay

### ISSUE THREAD

**Issue by frankleng** [mariusandra/pigeon-maps#7]
Love this project. @mariusandra 
was actually experimenting writing something like it, but you've gotten way further. 🥇  
is there's plan to support geojson overlay?

**Comment by mariusandra** [comment]
Thanks @frankleng!

I guess new features will be added on an "as needed" basis. This means if someone needs a feature and is willing to code it, it gets added.

I don't see myself needing GeoJSON any time soon, although I might look into circles and polylines in the beginning of next year. From there it shouldn't be hard to take it further.

It should be as easy as making an [overlay](https://github.com/mariusandra/pigeon-overlay), adding a <svg> on it, calling latLngToPixel a few times and then drawing the right paths and shapes.

Feel free to give it a crack if you have the time :smile:

**Comment by frankleng** [comment]
cool. thanks for the tip @mariusandra

**Comment by mariusandra** [comment]
Hi, closing this for now. If anyone needs and wants to make a GeoJSON plugin, feel free! See issue #31 on how to draw a random SVG on the map.

**Comment by mariusandra** [comment]
We now have official GeoJSON support! https://pigeon-maps.js.org/docs/geo-json-loader
