### ISSUE TITLE
defaultCenter and defaultZoom props

### ISSUE THREAD

**Issue by degroote22** [mariusandra/pigeon-maps#8]
i've been having issues using pigeon-maps and redux.
What happens is that I must listen to _onBoundsChanged_ but I'm not controlling the component.
So, whenever the map changes this function will create a redux action which will cause the map to re-render and then componentWillReceiveProps is called and it think that I'm controlling the component and it will check the difference between the zoom and center I'd set up and the one on the state.
What do you think about this api? defaultCenter and defaultZoom are used to bootstrap the app no longer checked.
Also, I'd like to know the bounds when I mount the component. What do you think about it?
I'll try to submit a pull request on the defaultCenter and defaultZoom and later I'll think about what shoud be done with the initial mounting.
Or we should call the onBoundsChange callback to call on first mounting.
Later on I'll tell my results.

**Comment by mariusandra** [comment]
About the callback when mounting, I think it makes sense to send an initial `onBoundsChange`, as the `bounds` changed from unknown to known. 

I pushed out [`v0.6.1`](https://github.com/mariusandra/pigeon-maps/releases/tag/v0.6.1) that does this
