### ISSUE TITLE
error 429, wikimedia throttling?

### ISSUE THREAD

**Issue by DWMiller** [mariusandra/pigeon-maps#83]
This is repeatable on the official demos, seeing a lot of failed requests to wikimedia on loading the map images. 

Did wikimedia change something that limits requests and potentially makes this unusable?

**Comment by seratonik** [comment]
Just started experiencing this as well, hopefully it's just temporary.

**Comment by nickimola** [comment]
Same here

**Comment by mariusandra** [comment]
Hi all, the wikimedia maps were never meant to be used by users of this library. I have no contract nor agreement with them. It's just an open tile server with maps that looked good enough, so I put them as default provider. Normally their maps are supposed to be only used on their properties, for example in Wikipedia.

You're instead supposed to have your own contract with a map tile provider and use those tiles.

Personally, we're currently using [MapTiler](https://www.maptiler.com/cloud/) in my company. Their free plan is generous enough for most needs.

So please change your tiles to something else and the problem will go away :).

There's a second question here regarding what should be the default tile layer for pigeon maps... and for the demo. I'm open to ideas and suggestions.

**Comment by nickimola** [comment]
> Hi all, the wikimedia maps were never meant to be used by users of this library. I have no contract nor agreement with them. It's just an open tile server with maps that looked good enough, so I put them as default provider. Normally their maps are supposed to be only used on their properties, for example in Wikipedia.
> 
> You're instead supposed to have your own contract with a map tile provider and use those tiles.
> 
> Personally, we're currently using [MapTiler](https://www.maptiler.com/cloud/) in my company. Their free plan is generous enough for most needs.
> 
> So please change your tiles to something else and the problem will go away :).
> 
> There's a second question here regarding what should be the default tile layer for pigeon maps... and for the demo. I'm open to ideas and suggestions.

Thanks for clarifying
How do we use a different tile? I couldn't see anything in the docs

**Comment by mariusandra** [comment]
Use the `provider` prop and see the [demo page code](https://github.com/mariusandra/pigeon-maps/blob/master/demo/demo.js) for samples.

**Comment by PabloSzx** [comment]
I think this problem should be addressed better in the documentation and examples, since even the website https://pigeon-maps.js.org/ has this problem still

**Comment by solegs** [comment]
Same issue

**Comment by beevelop** [comment]
Is there an issue for switching the default tile provider? IMHO using a defunct default provider hurts this library a bit.

**Comment by mariusandra** [comment]
Hey, I changed the default provider to OSM and added more documentation on how to change your provider. The fix is in `v0.15.0`
