### ISSUE TITLE
Tiles don't load with zoom > 10

### ISSUE THREAD

**Issue by darlantc** [mariusandra/pigeon-maps#84]
There is an error while zooming > 10. The tile images don't load, as you can see in the demo:

![Pigeon Maps error](https://dl.dropbox.com/s/vpqet2e69j1ox75/Screen%20Shot%202020-02-10%20at%2012.01.41.jpg)

**Comment by mddilley** [comment]
I ran into this same issue earlier today, but I then realized that it is an issue with the tile provider, Wikimedia, and not with this library. Try out the other providers in the demo, and they work great.

Here is how the provider is set in the demo. https://github.com/mariusandra/pigeon-maps/blob/4bb3d4ddf78cf1152da8c6462667e393b2b81790/demo/demo.js#L145

**Comment by darlantc** [comment]
Thanks @mddilley !

Changed to OSM provider.

**Comment by mariusandra** [comment]
Hi! Since 0.15 OSM is now the default provider.
