### ISSUE TITLE
429 error occurs

### ISSUE THREAD

**Issue by AndrewTkachenko** [mariusandra/pigeon-maps#97]
https://pigeon-maps.js.org/ 
https://prnt.sc/rlrk55 - 429 errors in network for map images

**Comment by cyberixae** [comment]
I have the same problem. I think it can be solved by switching tile provider. https://github.com/mariusandra/pigeon-maps#choose-a-tile-provider

**Comment by mariusandra** [comment]
I added a comment in the link above :).
Please upgrade to pigeon-maps 0.15.0 or later.
