### ISSUE TITLE
Creating a map from latitude and longitude shows a black and white map

### ISSUE THREAD

**Issue by GroovinChip** [mariusandra/pigeon-maps#98]
Our map data comes from https://pleiades.stoa.org/

Screenshot:
![uS6JQ7CCmq](https://user-images.githubusercontent.com/4250470/82357825-a5617c00-99d3-11ea-92c7-7527baf63b35.png)
Code:
```
<Map
  center={[
	this.state.mapData.reprPoint[1],
	this.state.mapData.reprPoint[0],
  ]}
  zoom={12}
  height={250}
></Map>
```

**Comment by GroovinChip** [comment]
@mariusandra Any thoughts on this? Is this expected behavior?

**Comment by mariusandra** [comment]
@GroovinChip , sorry, no idea. I haven't seen anything like this before. Just investigate where the images are being loaded from (via the network tab in devtools/"inspect") to get an idea what might be happening.
Also, is this happening on every zoom level? With all coordinates? 
What if you give a provider?

**Comment by GroovinChip** [comment]
I am using a different implementation now. Thanks for your help.

**Comment by bouiboui** [comment]
This is the default renderer (Stamen Toner).
A better default might be Stamen Terrain, which is less stylized:
```tsx

function stamenTerrain(x: number, y: number, z: number, dpr: number) {
  return `https://stamen-tiles.a.ssl.fastly.net/terrain/${z}/${x}/${y}${dpr >= 2 ? '@2x' : ''}.png`
}

[...]

  <Map provider={stamenTerrain}
```
![image](https://user-images.githubusercontent.com/3274103/106348376-15940180-62c6-11eb-8de3-64d3a0d9be18.png)
